name: JustChat
version: '${version}'
main: fr.ht06.justchat.JustChat
api-version: '1.20'
author: ht06
softdepend: ["PlaceholderAPI"]
commands:
  justchat:
    description: a help command for the plugin JustChat

